version: '2'
services:
  webserver:
    container_name: webserver
    image: webdevops/php-nginx-dev:7.3
    environment:
      - DBHOST=dbserver
      - DBUSER=admin
      - DBPASS=Secret*123
      - DBPORT=3306
      - DBNAME=base_apoio
      - RABBITMQ_HOST=queueserver
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - REDIS_HOST=cacheserver
      - REDIS_PORT=6379
      - REDIS_USER=guest
      - REDIS_PASSWORD=guest
    depends_on:
      - dbserver
    links:
      - dbserver:dbserver
    restart: always
    expose:
      - 80
    volumes:
      - .:/app
      - ./.docker/nginx/app.conf:/etc/nginx/sites-enabled/app.conf
    env_file:
      - ./.docker/php/.env
    networks:
      net:
        ipv4_address: 172.0.0.2
  dbserver:
    container_name: dbserver
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - ./.docker/volume/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      net:
        ipv4_address: 172.0.0.3
  rabbitmq:
    image: rabbitmq:management
    container_name: queueserver
    volumes:
      - ./.docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      net:
        ipv4_address: 172.0.0.4
  redis:
    image: redis:latest
    container_name: cacheserver
    restart: always
    expose:
      - 6379
    networks:
      net:
        ipv4_address: 172.0.0.5
networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
